/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        int a[26] = {0};
        for(int i = 0;i < s.length();i++){
            a[s[i]-'a']++;
        }
        
        for(int i = 0;i < t.length();i++){
            if(a[t[i]-'a'] == 0){
                return t[i];
            }
            else{
                a[t[i]-'a']--;
            }
        }
        return 'a';
    }
};
